# Generated by Django 6.0.2 on 2026-02-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('C', 'C — Asosiy daraja'), ('CP', 'C+ — Kengaytirilgan C'), ('B', "B — O'rta daraja"), ('BP', 'B+ — Kengaytirilgan B'), ('A', 'A — Yuqori daraja'), ('AP', 'A+ — Mukammal daraja')], max_length=2, verbose_name='Daraja')),
                ('text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=200, verbose_name='Variant A')),
                ('option_b', models.CharField(max_length=200, verbose_name='Variant B')),
                ('option_c', models.CharField(max_length=200, verbose_name='Variant C')),
                ('option_d', models.CharField(max_length=200, verbose_name='Variant D')),
                ('correct_answer', models.IntegerField(choices=[(0, 'A'), (1, 'B'), (2, 'C'), (3, 'D')], verbose_name="To'g'ri javob")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Savol',
                'verbose_name_plural': 'Savollar',
                'ordering': ['level', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, verbose_name='Sessiya')),
                ('user_name', models.CharField(blank=True, max_length=100, verbose_name='Foydalanuvchi ismi')),
                ('level', models.CharField(choices=[('C', 'C — Asosiy daraja'), ('CP', 'C+ — Kengaytirilgan C'), ('B', "B — O'rta daraja"), ('BP', 'B+ — Kengaytirilgan B'), ('A', 'A — Yuqori daraja'), ('AP', 'A+ — Mukammal daraja')], max_length=2, verbose_name='Daraja')),
                ('score', models.IntegerField(verbose_name="To'g'ri javoblar")),
                ('total', models.IntegerField(default=45, verbose_name='Jami savollar')),
                ('grade', models.CharField(max_length=10, verbose_name='Baho')),
                ('percentage', models.FloatField(verbose_name='Foiz')),
                ('time_taken', models.IntegerField(default=0, verbose_name='Sarflangan vaqt (soniya)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sana')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP manzil')),
            ],
            options={
                'verbose_name': 'Natija',
                'verbose_name_plural': 'Natijalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
